### ISSUE TITLE
Bundle can't contain `noteType`

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/i2b2-phi-dataset#14]
We removed support for `noteType` awhile ago and changed this just to `type`.

**Comment by tschaffter** [comment]
@thomasyu888 This is actually correct. We are using `noteType`, `addressType`, `idType` and `contactType`. The motivation is the following: The schema objects are "annotation", e.g. `TextContactAnnotation`. According to best coding practice, if adding a `type` property would mean the "type of the annotation", while it's more precision to say that it's the type of "contact information". That's why I using `contactType`, e.g. is more descriptive.

Another motivation is related to the fact that we are using inheritance in these annotation schemas, e.g. `TextContactAnnotation` extends `TextAnnotation`. Using MongoDB and maybe other database, there is a technique to store different schemas that share the same parent schema in the same mongo DB collection. This would be implemented using a "discriminator" object property, that would typically be "TextAnnotation.type" where type would take a value like "address", "contact", etc. that is the type of the annotation. We are currently not locking us out of this option with the current property naming.

Tagging @cascadianblue

**Comment by thomasyu888** [comment]
@tschaffter If you look at the note schema: https://nlpsandbox.github.io/nlpsandbox-schemas/data-node/latest/docs/#tag/Note, you will see that it accepts `type` and not `noteType`

**Comment by tschaffter** [comment]
@thomasyu888 This should now be fixed in the JSON files release a couple of days ago.
