### ISSUE TITLE
Use `synapser` instead of reticulate + conda

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/i2b2-phi-dataset#15]
Theres no reason to add more complexity when everything can be achieved within R.  That being said, this isn't required and there is nothing wrong with the way things are done.

That being said... It's true that by using `reticulate` and the synapsePythonClient, you're ensuring that you always have the most up to date client.  But looking at the Rmarkdown file, since you are only doing a `synGet`, it seems excessive to add so many dependencies.

**Comment by tschaffter** [comment]
@thomasyu888 I don't like Synapser because several of its function returns weird Python objects that no one knows how to use, including the developer of Synapser I think. I mentioned this on the Sage slack R channel some times ago. Sage even has a fork of this library used to return weird R object that supposedly contain information from Python.

Another issue with Synapser is that I've met cases where Python has an error that is not propagate to R, which make it then impossible to try-catch and deal appropriately. I probably won't use Synapser in the future. This is one of the reason I decided to add develop [this project](https://github.com/tschaffter/rstudio) where R and Python can be used together. A fork of this project now lives here: https://github.com/Sage-Bionetworks/docker-rstudio
